---
- name: Install Apache and upload web page
  hosts: all
  become: yes

  vars:
   source_folder: ./web_site/
   destination_folder: /var/www/html

  tasks: 
  - name: Install Apache web servers
    apt: name=apache2 state=latest

  - name: Copy site to web servers
    copy: src={{ source_folder }} dest={{ destination_folder }} mode=0555
    notify: Restart Apache

  - name: Start Apache and enable it on the every boot
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
